"""Initial migration

Revision ID: 5f0ff0bb02b1
Revises: 
Create Date: 2024-08-01 11:37:49.720813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f0ff0bb02b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('rooms')
    op.drop_table('hotels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('guest_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bedroom_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bathroom_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amenities', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('host_information', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('slug', name='hotels_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('rooms',
    sa.Column('room_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hotel_slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('room_image', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('room_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bedroom_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hotel_slug'], ['hotels.slug'], name='rooms_hotel_slug_fkey'),
    sa.PrimaryKeyConstraint('room_slug', name='rooms_pkey')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
